<?php if (!defined('APPLICATION')) exit();
// DO NOT EDIT THIS FILE. If you want to override the settings in this file then edit config.php.
// This is the global application configuration file that sets up default values for configuration settings.
${DOLLAR}Configuration = [];

// Auto-enable some addons.
${DOLLAR}Configuration['EnabledPlugins']['stubcontent'] = true;
${DOLLAR}Configuration['EnabledPlugins']['swagger-ui'] = true;
${DOLLAR}Configuration['EnabledApplications']['Dashboard'] = 'dashboard';
${DOLLAR}Configuration['EnabledPlugins']['rich-editor'] = true;

// ImageUpload
${DOLLAR}Configuration['ImageUpload']['Limits']['Enabled'] = false;
${DOLLAR}Configuration['ImageUpload']['Limits']['Width'] = '1000';
${DOLLAR}Configuration['ImageUpload']['Limits']['Height'] = '1400';

// Database defaults.
${DOLLAR}Configuration['Database']['Engine'] = 'MySQL';
${DOLLAR}Configuration['Database']['Host'] = '${DATABASE_HOST}';
${DOLLAR}Configuration['Database']['Name'] = '${DATABASE_NAME}';
${DOLLAR}Configuration['Database']['User'] = '${DATABASE_USER}';
${DOLLAR}Configuration['Database']['Password']  = '${DATABASE_PASSWORD}';
${DOLLAR}Configuration['Database']['CharacterEncoding'] = 'utf8mb4';
${DOLLAR}Configuration['Database']['DatabasePrefix'] = 'GDN_';
${DOLLAR}Configuration['Database']['ExtendedProperties']['Collate'] = 'utf8mb4_unicode_ci';
${DOLLAR}Configuration['Database']['ConnectionOptions'] = [
    12 => false, // PDO::ATTR_PERSISTENT
    1000 => true, // PDO::MYSQL_ATTR_USE_BUFFERED_QUERY (missing in some PHP installations)
];

// Use a dirty cache by default. Try Vanilla with memcached!
${DOLLAR}Configuration['Cache']['Enabled'] = true;
${DOLLAR}Configuration['Cache']['Method'] = 'dirtycache';
${DOLLAR}Configuration['Cache']['Filecache']['Store']  = PATH_CACHE.'/Filecache';

// Technical content stuff.
${DOLLAR}Configuration['Garden']['ContentType'] = 'text/html';
${DOLLAR}Configuration['Garden']['Locale'] = 'en';
${DOLLAR}Configuration['Garden']['LocaleCodeset'] = 'UTF8';

${DOLLAR}Configuration['HotReload']['IP'] = '127.0.0.1';
${DOLLAR}Configuration['HotReload']['Enabled'] = false;

${DOLLAR}Configuration['ContentSecurityPolicy']['ScriptSrc']['AllowedDomains'] = [];

// Site specifics.
${DOLLAR}Configuration['Garden']['Installed'] = false; // Has Garden been installed yet? This blocks setup when true.
${DOLLAR}Configuration['Garden']['Title'] = 'Vanilla';
${DOLLAR}Configuration['Garden']['Domain'] = '';
${DOLLAR}Configuration['Garden']['WebRoot'] = false; // You can set this value if you are using htaccess to direct into the application, but the correct webroot isn't being recognized.
${DOLLAR}Configuration['Garden']['StripWebRoot'] = false;
${DOLLAR}Configuration['Garden']['AllowSSL'] = true;
${DOLLAR}Configuration['Garden']['PrivateCommunity'] = false;
${DOLLAR}Configuration['Garden']['Forms']['HoneypotName'] = 'hpt';
${DOLLAR}Configuration['Feature']['DeferredLegacyScripts']['Enabled'] = true;

// Developer stuff.
${DOLLAR}Configuration['Garden']['Debug'] = true;
${DOLLAR}Configuration['Garden']['Errors']['LogFile'] = '';
${DOLLAR}Configuration['Garden']['FolderBlacklist'] = ['.', '..', '_svn', '.git']; // Folders we should never search for classes.

// User registration & authentication.
${DOLLAR}Configuration['Garden']['Session']['Length'] = '15 minutes';
${DOLLAR}Configuration['Garden']['Cookie']['Salt'] = ''; // We do this during setup, chill.
${DOLLAR}Configuration['Garden']['Cookie']['Name'] = 'Vanilla';
${DOLLAR}Configuration['Garden']['Cookie']['Path']  = '/';
${DOLLAR}Configuration['Garden']['Cookie']['Domain'] = '';
${DOLLAR}Configuration['Garden']['Cookie']['HashMethod'] = 'md5'; // md5 or sha1
${DOLLAR}Configuration['Garden']['Authenticator']['DefaultScheme'] = 'password'; // Types include 'Password', 'Handshake', 'Openid'
${DOLLAR}Configuration['Garden']['Authenticator']['RegisterUrl'] = '/entry/register?Target=%2${DOLLAR}s';
${DOLLAR}Configuration['Garden']['Authenticator']['SignInUrl'] = '/entry/signin?Target=%2${DOLLAR}s';
${DOLLAR}Configuration['Garden']['Authenticator']['SignOutUrl'] = '/entry/signout/{Session_TransientKey}?Target=%2${DOLLAR}s';
${DOLLAR}Configuration['Garden']['Authenticator']['EnabledSchemes'] = ['password'];
${DOLLAR}Configuration['Garden']['Authenticator']['SyncScreen'] = "smart";
${DOLLAR}Configuration['Garden']['Authenticators']['password']['Name'] = "Password";
${DOLLAR}Configuration['Garden']['UserAccount']['AllowEdit'] = true; // Allow users to edit their account information? (SSO requires accounts be edited in external system).
${DOLLAR}Configuration['Garden']['Registration']['Method'] = 'Captcha'; // Options are: Basic, Captcha, Approval, Invitation
${DOLLAR}Configuration['Garden']['Registration']['InviteExpiration'] = '1 week'; // When invitations expire. This will be plugged into strtotime().
${DOLLAR}Configuration['Garden']['Registration']['InviteRoles'] = 'FALSE';
${DOLLAR}Configuration['Garden']['Registration']['ConfirmEmail'] = false;
${DOLLAR}Configuration['Garden']['Registration']['MinPasswordLength'] = 6;
${DOLLAR}Configuration['Garden']['Registration']['NameUnique'] = true;
${DOLLAR}Configuration['Garden']['TermsOfService'] = '/home/termsofservice'; // The url to the terms of service.
${DOLLAR}Configuration['Garden']['Password']['MinLength'] = 6;
${DOLLAR}Configuration['Garden']['Roles']['Manage'] = true; // @deprecated

// Garden security features
${DOLLAR}Configuration['Garden']['Security']['Hsts']['IncludeSubDomains'] = false;
${DOLLAR}Configuration['Garden']['Security']['Hsts']['Preload'] = false;
${DOLLAR}Configuration['Garden']['Security']['Hsts']['MaxAge'] = 604800;

// Outgoing email.
${DOLLAR}Configuration['Garden']['Email']['UseSmtp'] = false;
${DOLLAR}Configuration['Garden']['Email']['SmtpHost'] = '';
${DOLLAR}Configuration['Garden']['Email']['SmtpUser'] = '';
${DOLLAR}Configuration['Garden']['Email']['SmtpPassword'] = '';
${DOLLAR}Configuration['Garden']['Email']['SmtpPort'] = '25';
${DOLLAR}Configuration['Garden']['Email']['SmtpSecurity'] = ''; // ssl/tls
${DOLLAR}Configuration['Garden']['Email']['MimeType'] = 'text/plain';
${DOLLAR}Configuration['Garden']['Email']['SupportName'] = 'Support';
${DOLLAR}Configuration['Garden']['Email']['SupportAddress'] = '';

// Contact with the mothership.
${DOLLAR}Configuration['Garden']['UpdateCheckUrl'] = 'https://open.vanillaforums.com/addons/update';
${DOLLAR}Configuration['Garden']['AddonUrl'] = 'https://open.vanillaforums.com/addons';
${DOLLAR}Configuration['Garden']['VanillaUrl'] = 'https://open.vanillaforums.com';

// File handling.
${DOLLAR}Configuration['Garden']['CanProcessImages'] = false;
${DOLLAR}Configuration['Garden']['Upload']['MaxFileSize'] = '50M';
${DOLLAR}Configuration['Garden']['Upload']['AllowedFileExtensions'] = [
    'txt', 'jpg', 'jpeg', 'gif', 'png', 'bmp', 'tiff', 'ico', 'zip', 'gz', 'tar.gz', 'tgz', 'psd', 'ai', 'pdf', 'doc', 'xls', 'ppt', 'docx', 'xlsx', 'pptx', 'log', 'rar', '7z'
];
${DOLLAR}Configuration['Garden']['Profile']['MaxHeight'] = 560;
${DOLLAR}Configuration['Garden']['Profile']['MaxWidth'] = 560;
${DOLLAR}Configuration['Garden']['Thumbnail']['Size'] = 200;

// Appearance.
${DOLLAR}Configuration['Garden']['Theme'] = 'theme-foundation';
${DOLLAR}Configuration['Garden']['MobileTheme'] = 'theme-foundation';
${DOLLAR}Configuration['Garden']['Menu']['Sort'] = ['Dashboard', 'Discussions', 'Questions', 'Activity', 'Applicants', 'Conversations', 'User'];
${DOLLAR}Configuration['Garden']['ThemeOptions']['Styles']['Key'] = 'Default';
${DOLLAR}Configuration['Garden']['ThemeOptions']['Styles']['Value'] = '%s_default';

// Profiles.
${DOLLAR}Configuration['Garden']['Profile']['Public']= true;
${DOLLAR}Configuration['Garden']['Profile']['ShowAbout'] = true;
${DOLLAR}Configuration['Garden']['Profile']['EditPhotos'] = true; // false to disable user photo editing
${DOLLAR}Configuration['Garden']['Profile']['EditUsernames'] = false;
${DOLLAR}Configuration['Garden']['BannedPhoto'] = 'https://images.v-cdn.net/banned_large.png';

// Embedding forum & comments.
${DOLLAR}Configuration['Garden']['Embed']['CommentsPerPage'] = 50;
${DOLLAR}Configuration['Garden']['Embed']['SortComments'] = 'desc';
${DOLLAR}Configuration['Garden']['Embed']['PageToForum'] = true;
${DOLLAR}Configuration['Garden']['SignIn']['Popup'] = true; // Should the sign-in link pop up or go to it's own page? (SSO requires going to it's own external page)

// User experience & formatting.
${DOLLAR}Configuration['Garden']['InputFormatter'] = 'Rich'; // Html, BBCode, Markdown, Text, Rich
${DOLLAR}Configuration['Garden']['MobileInputFormatter'] = 'Rich';
${DOLLAR}Configuration['Garden']['Html']['AllowedElements'] = "a, abbr, acronym, address, area, audio, b, bdi, bdo, big, blockquote, br, caption, center, cite, code, col, colgroup, dd, del, details, dfn, div, dl, dt, em, figure, figcaption, font, h1, h2, h3, h4, h5, h6, hgroup, hr, i, img, ins, kbd, li, map, mark, menu, meter, ol, p, pre, q, s, samp, small, span, strike, strong, sub, sup, summary, table, tbody, td, tfoot, th, thead, time, tr, tt, u, ul, var, video, wbr";
${DOLLAR}Configuration['Garden']['Html']['AllowedUrlSchemes'] = [
    'aim', 'feed', 'file', 'ftp', 'gopher', 'http', 'https', 'irc', 'mailto', 'news', 'nntp', 'rapidminer', 'sftp', 'ssh', 'telnet'
];
${DOLLAR}Configuration['Garden']['Search']['Mode'] = 'boolean'; // matchboolean, match, boolean, like
${DOLLAR}Configuration['Garden']['EditContentTimeout'] = 3600; // -1 means no timeout. 0 means immediate timeout. > 0 is in seconds. 60 * 60 = 3600 (aka 1hr)
${DOLLAR}Configuration['Garden']['Format']['Mentions'] = true;
${DOLLAR}Configuration['Garden']['Format']['Hashtags'] = false;
${DOLLAR}Configuration['Garden']['Format']['YouTube'] = true;
${DOLLAR}Configuration['Garden']['Format']['Vimeo'] = true;
${DOLLAR}Configuration['Garden']['Format']['EmbedSize'] = 'normal'; // tiny/small/normal/big/huge or WIDTHxHEIGHT

// Default preferences. Setting these to 'false' disables them globally.
${DOLLAR}Configuration['Preferences']['Email']['ConversationMessage'] = '1';
${DOLLAR}Configuration['Preferences']['Email']['BookmarkComment'] = '1';
${DOLLAR}Configuration['Preferences']['Email']['ParticipateComment'] = '0';
${DOLLAR}Configuration['Preferences']['Email']['WallComment'] = '0';
${DOLLAR}Configuration['Preferences']['Email']['ActivityComment'] = '0';
${DOLLAR}Configuration['Preferences']['Email']['DiscussionComment'] = '0';
${DOLLAR}Configuration['Preferences']['Email']['Mention'] = '0';
${DOLLAR}Configuration['Preferences']['Popup']['ConversationMessage'] = '1';
${DOLLAR}Configuration['Preferences']['Popup']['BookmarkComment'] = '1';
${DOLLAR}Configuration['Preferences']['Popup']['ParticipateComment'] = '0';
${DOLLAR}Configuration['Preferences']['Popup']['WallComment'] = '1';
${DOLLAR}Configuration['Preferences']['Popup']['ActivityComment'] = '1';
${DOLLAR}Configuration['Preferences']['Popup']['DiscussionComment'] = '1';
${DOLLAR}Configuration['Preferences']['Popup']['Mention'] = '1';

// Module visibility and sorting.
${DOLLAR}Configuration['Garden']['Modules']['ShowGuestModule'] = true;
${DOLLAR}Configuration['Garden']['Modules']['ShowSignedInModule'] = false;
${DOLLAR}Configuration['Garden']['Modules']['ShowRecentUserModule'] = false;
${DOLLAR}Configuration['Modules']['Dashboard']['Panel'] = ['MeModule', 'UserBoxModule', 'ActivityFilterModule', 'UserPhotoModule', 'ProfileFilterModule', 'SideMenuModule', 'UserInfoModule', 'GuestModule', 'Ads'];
${DOLLAR}Configuration['Modules']['Dashboard']['Content'] = ['MessageModule', 'MeModule', 'UserBoxModule', 'ProfileOptionsModule', 'Notices', 'ActivityFilterModule', 'ProfileFilterModule', 'Content', 'Ads'];
${DOLLAR}Configuration['Modules']['Vanilla']['Panel'] = ['MeModule', 'UserBoxModule', 'GuestModule', 'NewDiscussionModule', 'DiscussionFilterModule', 'SignedInModule', 'Ads'];
${DOLLAR}Configuration['Modules']['Vanilla']['Content'] = ['MessageModule', 'MeModule', 'UserBoxModule', 'NewDiscussionModule', 'ProfileOptionsModule', 'Notices', 'NewConversationModule', 'NewDiscussionModule', 'DiscussionFilterModule', 'CategoryModeratorsModule', 'Content', 'Ads'];
${DOLLAR}Configuration['Modules']['Conversations']['Panel'] = ['MeModule', 'UserBoxModule', 'NewConversationModule', 'SignedInModule', 'GuestModule', 'Ads'];
${DOLLAR}Configuration['Modules']['Conversations']['Content'] = ['MessageModule', 'MeModule', 'UserBoxModule', 'NewConversationModule', 'Notices', 'Content', 'Ads'];

// Routes.
${DOLLAR}Configuration['Routes']['DefaultController'] = 'discussions';
${DOLLAR}Configuration['Routes']['DefaultForumRoot'] = 'discussions';
${DOLLAR}Configuration['Routes']['Default404'] = ['dashboard/home/filenotfound', 'NotFound'];
${DOLLAR}Configuration['Routes']['DefaultPermission'] = ['dashboard/home/unauthorized', 'NotAuthorized'];
${DOLLAR}Configuration['Routes']['UpdateMode'] = 'dashboard/home/updatemode';

// Themes
${DOLLAR}Configuration['Theme']['Banner']['VisibleSections'] = ["DiscussionList", "CategoryDiscussionList", "CategoryList", "NewEventList"];

// Plugins.Sphinx.Server
${DOLLAR}Configuration['Plugins']['Sphinx']['Server'] = '${SPHINX_SERVER}';
